config/routes.rb
Rails.application.routes.draw do
  # 会員
  devise_for :users,skip: [:passwords,], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # ユーザー
  scope module: :user do
    root to: "homes#top"
    get "about" => "homes#about"
    resources :users, only: [:show, :edit, :update] do
      collection do
        get "unsubscribe"
        patch "withdraw"
      end
    end
    resources :posts do
      resource :likes, only:[:create, :destroy]
      resources :comments, only:[:create, :destroy]
    end

    resources :users do
      resource :relationships, only:[:create, :destroy]
      get :followings, on: :member
      get :followers, on: :member
    end
    get  'index' =>'messages#index'
    post 'confirm' => 'messages#confirm'
    post 'back', to: 'messages#back'
    post 'done' => 'messages#done'

    get 'search' => 'posts#search'
    get 'rank' => 'ranks#rank'
    get 'training' => 'trainings#training'
  end

  # 管理者
  namespace :admin do
    root to:"homes#top"
    resources :users, only:[:index, :edit, :update]
    resources :posts do
    resources :comments, only:[:destroy]
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following
  attachment :profile_image, destroy: false

  validates :name, presence: true

  def already_likes?(post)
    self.likes.exists?(post_id: post.id)
  end

# フォローしているか確認
  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

# 会員ステータス　論理削除
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page]).per(8)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]= "会員情報を変更しました"
      redirect_to admin_users_path
    else
      flash[:alert]= "会員情報の変更に失敗しました"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :is_deleted)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment =  Comment.find_by(id: params[:id], post_id: params[:post_id])
    @comment.destroy
    @comment = Comment.new
  end

   private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @posts = Post.all.order(id: "DESC")
    # 最新の投稿が表示されるようにIDを降順で設定
  end

  def about
  end
end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    like = @post.likes.new(user_id: current_user.id)
    like.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @likes = current_user.likes.find_by(post_id: @post.id)
    @likes.destroy
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  before_action :authenticate_user!
  def index
    # 入力画面
    @message = Message.new
  end

  def confirm
    # 入力確認
    @message = Message.new(message_params)
    if @message.valid?
      # 成功なら確認画面へ
      render :action => 'confirm'
    else
      # 失敗なら入力画面へ
      flash[:alert] = "必要事項を入力してください"
      render :action => 'index'
    end
  end

  def back
    # 内容を保存したまま戻る
    @message = Message.new(message_params)
    render :action => 'index'
  end

  def done
    # メール送信
    @message = Message.new(message_params)
    if params[:back]
      render :action => 'index'
    else
      # 今すぐ送信
      MessageMailer.received_email(@message).deliver_now
      render :action => 'done'
    end
  end

  private
  def message_params
    params.require(:message).permit(:name, :email, :content)
  end

end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only:[:edit, :update]
  #他のユーザーのpostを変更できないようにする

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "新規投稿しました"
    redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    @posts = Post.all.order(id: 'DESC').page(params[:page]).per(6)
    @user = current_user

  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.user_id = current_user.id
    if @post.update(post_params)
      flash[:notice] = "更新しました"
      redirect_to post_path
    else
      render 'edit'
    end
  end

# 検索
  def search
    @posts = Post.search(params[:keyword]).page(params[:page]).per(6)
    @keyword = params[:keyword]
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "削除しました"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

  def ensure_correct_user
    @post = Post.find(params[:id])
     unless @post.user == current_user
     redirect_to posts_path
     end
  end
end

app/controllers/user/ranks_controller.rb
class User::RanksController < ApplicationController
  def rank
  @post_like_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').pluck(:post_id))
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController

  def create
    following = current_user.relationships.build(follower_id: params[:user_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    following.destroy
    redirect_to request.referrer || root_path
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

   before_action :reject_user, only: [:create]

  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:notice] = "このアカウントは管理者によって制限されています"
        redirect_to new_user_session_path
      end
    else
    end
  end
end

app/controllers/user/trainings_controller.rb
class User::TrainingsController < ApplicationController
  def training
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]
  #他のユーザーを編集できないように

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: 'DESC')
    # 新着順(降順)で表示
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "会員情報を更新しました"
      redirect_to user_path(@user)
    else
      flash[:alert] = "必要事項を入力してください"
      render "edit"
    end
  end

  def index
    @users = User.where.not(id: current_user.id).page(params[:page]).per(8)
    @posts = Post.all
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
    @user = User.find(params[:id])
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
    @user = User.find(params[:id])
  end

  def withdraw
    @user = current_user
    @user.destroy
    reset_session
    flash[:notice] = "退会しました"
    redirect_to root_path
  end

  private
  def user_params
      params.require(:user).permit(:name, :email, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/user/users/_info.html.erb
<h4>ユーザー情報</h4>
<%= link_to user_path(user.id)  do %>
  <%= attachment_image_tag user, :profile_image, format: "jpeg", size:"200x200", fallback: "no_image.jpg",class:"rounded-circle mx-auto mb-4"; %>
<% end %>
<h5>ニックネーム</h5>
<%= user.name %><br>
<% if current_user != user %>
  <% if user.is_followed_by?(current_user) %>
    <%= link_to user_relationships_path(user), method: :delete do %>
    <button class = "btn btn-primary mt-2 mb-2">フォローを外す</button>
    <% end %>
  <% else%>
    <%= link_to user_relationships_path(user), method: :post do %>
    <button class = "btn btn-success mt-2 mb-2">フォローする</button>
    <% end %>
  <% end %>
<% end %>

<% if current_user == user %>
  <br><%= link_to "編集", edit_user_path(user),class: "fas fa-user-cog btn btn-outline-secondary btn-block mt-3 mr-3 mb-3" %>
<% end %>
<br>
<p><%= link_to followings_user_path(user), class:"btn btn-dark mt-3 btn-sm" do %>
  <%= user.followings.count %>フォロー
<% end %>

<%= link_to followers_user_path(user), class:"btn btn-dark mt-3 btn-sm" do %>
  <%= user.followers.count %>フォロワー
<% end %></p>

app/views/user/users/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-7 mx-auto">
      <h2>ユーザー情報編集</h2>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
        <%= f.label :"ニックネーム" %><br>
        <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :"メールアドレス" %><br>
        <%= f.text_field :email, class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.label :"プロフィール画像" %><br>
        <%= f.attachment_field :profile_image %>
        </div>
        <%= f.submit "更新する", class: "btn btn-success mt-3" %>
      　<%= link_to "退会", unsubscribe_users_path(@user), class: "btn btn-danger mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/user/users/followers.html.erb
<div class= "container">
  <div class= "row ml-5 mt-4">
    <div class= "col-md-9 mx-auto">
      <table class='table'>
        <h2><%= @user.name %>さんがフォローされているユーザー</h2>
        <% if @users.present? %>
          <thead>
            <tr>
              <th>画像</th>
              <th>ニックネーム</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50') %></td>
                <td><%= user.name %></td>
                <td><%= user.followings.count %>フォロー</td>
                <td><%= user.followers.count %>フォロワー</td>
                <td><%= link_to '詳細', user_path(user), class: "user_#{user.id} btn btn-dark" %></td>
              </tr>
            <% end %>
          </tbody>
       </table>
      <% else %>
        ユーザーはいません
      <% end %>
    </div>
  </div>
</div>

app/views/user/users/followings.html.erb
<div class= "container">
  <div class= "row ml-5 mt-4">
    <div class= "col-md-9 mx-auto">
      <table class='table'>
        <h2><%= @user.name %>さんがフォローしたユーザー</h2>
          <% if @users.present? %>
            <thead>
              <tr>
               <th>画像</th>
               <th>ニックネーム</th>
               <th></th>
               <th></th>
               <th></th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50') %></td>
                  <td><%= user.name %></td>
                  <td><%= user.followings.count %>フォロー</td>
                  <td><%= user.followers.count %>フォロワー</td>
                  <td><%= link_to '詳細', user_path(user), class: "user_#{user.id} btn btn-dark" %></td>
                </tr>
              <% end %>
            </tbody>
          <% else %>
          ユーザーはいません
          <% end %>
      </table>
    </div>
  </div>
</div>

app/views/user/users/index.html.erb
<div class= "container">
  <div class= "row ml-5 mt-4">
    <div class= "col-md-9 mx-auto">
      <table class= "table">
        <h2>すべてのユーザー</h2>
        <thead>
          <th>画像</th>
          <th>ニックネーム</th>
          <th>フォロー</th>
          <th>フォロワー</th>
          <th></th>
          <th></th>
        </thead>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:'50x50' %></td>
          <td><%= user.name %></td>
          <td><%= user.followings.count %>フォロー</td>
          <td><%= user.followers.count %>フォロワー</td>
          <td><%= link_to '詳細', user_path(user.id), class:"btn btn-dark" %></td>
          <% end %>
        </tr>
        </tbody>
      </table>
   </div>
  </div>
</div>

<div class="row  justify-content-center mt-5">
  <%= paginate @users, theme: 'twitter-bootstrap-4' %>
</div>

app/views/user/users/show.html.erb
<div class="container">
  <h2 class="text-center mt-3 mb-5"><%= @user.name %>さんの投稿</h2>
  <div class="row">
    <div class="text-center col-md-3">
      <%= render 'user/users/info', user: @user %>
    </div>
      <% @posts.each do |post| %>
        <div class="col-md-3 mt-4">
          <%= link_to post_path(post.id) do %>
            <%= attachment_image_tag post, :image,size:"300x200",fallback: "no_image.jpg", class:"card-img-top"; %>
          <% end %>
          <div class="card"%>
            <div class="card-body text-center">
              <h4 class="card-title"><%=post.title %></h4>
              <div class="row">
                <div class="col-9 mx-auto">
                  <span><%= link_to post_path(post.id), class:"text-dark" do %></span>
                    <i class="far fa-comment mb-3"> <%= post.comments.count %></i>
                  <% end %>
                  <p id="like_buttons_<%= post.id %>">
                    <%= render 'user/likes/like', post: post %>
                  </p>
                  <p><%= post.created_at.strftime('%Y/%m/%d') %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/user/users/unsubscribe.html.erb
<div class = 'container'>
  <div class = 'row text-center mt-5'>
    <div class ='col-md-9 mx-auto' >
      <p><strong>本当に退会しますか？</strong></p><br>
      <p>退会すると、会員情報や</p>
      <p>これまでの投稿が削除され、閲覧できなくなります。</p>
      <p>退会する場合は、「退会する」をクリックしてください。</p>
      <p><%= link_to '退会しない', root_path, class: 'btn btn-primary mr-3 mt-5'%>
        <%= link_to '退会する', withdraw_users_path, method: :patch,"data-confirm" => "本当に退会しますか？", class: 'btn btn-danger ml-3 mt-5'  %></p>
    </div>
  </div>
</div>